language: cpp
sudo: false
matrix:
  include:
  - compiler: clang
    os: osx
  - compiler: gcc
    os: linux
script:
- make -j
- wget https://github.com/parallaxinc/spin-standard-library/archive/1.0.0.zip
- unzip 1.0.0.zip
- pushd spin-standard-library-1.0.0/
- wget https://github.com/lamestation/lamestation-sdk/releases/download/rc2-0.3.2/lamestation-sdk-rc2-0.3.2.zip
- unzip lamestation-sdk-rc2-0.3.2.zip
- SPINC='../build/openspin -qu' ./test.sh
- popd
after_script:
- cppcheck --enable=all -q `git ls-files *.cpp`
deploy:
  provider: releases
  api_key:
    secure: WTNNiO6l29NG86dkDj89P/RuPBZItG2IbY5guzAeiJflGvnDCUY5cpMpEqEyavYQVLOosayJiqr0VV1qIAQ20Su6C6gfrLo5rnx7JvnRqgeIFgWA9JByYICfWVCzV1gYijl8W6+oMAApODWw9dpLk37rfWi9U7FprsynWEfUP8A=
  file_glob: true
  file: openspin.*.zip
  skip_cleanup: true
  on:
    repo: bweir/OpenSpin
    tags: true
    all_branches: true
