language: cpp
sudo: false
matrix:
  include:
  - compiler: clang
    os: osx
  - compiler: clang
    os: linux
    env: QMAKESPEC=linux-clang
  - compiler: gcc
    os: linux
script:
- make -j4
after_script:
- cppcheck --enable=all -q `git ls-files *.cpp`
deploy:
  provider: releases
  api_key:
    secure: WTNNiO6l29NG86dkDj89P/RuPBZItG2IbY5guzAeiJflGvnDCUY5cpMpEqEyavYQVLOosayJiqr0VV1qIAQ20Su6C6gfrLo5rnx7JvnRqgeIFgWA9JByYICfWVCzV1gYijl8W6+oMAApODWw9dpLk37rfWi9U7FprsynWEfUP8A=
  file: openspin
  on:
    repo: bweir/OpenSpin
